# Generated by Django 5.0.6 on 2024-05-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='qntDias',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
