# Generated by Django 5.0.6 on 2024-06-04 18:16

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0002_usuario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=14, verbose_name='cpf'),
        ),
    ]
