# Generated by Django 5.0.6 on 2024-05-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0002_alter_reserva_qntdias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupons',
            name='codigo',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
