# Generated by Django 5.0.6 on 2024-05-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0002_apartamento_valor_reserva_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='dataEntrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='dataSaida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
