# Generated by Django 5.0.6 on 2024-06-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0004_usuario_celular_usuario_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamento',
            name='foto',
            field=models.ImageField(default=1, upload_to='fotos_apartamento'),
            preserve_default=False,
        ),
    ]
