# Generated by Django 5.0.6 on 2024-05-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0004_alter_cupons_codigo_alter_cupons_utilizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='qntDatas',
            field=models.IntegerField(default=0),
        ),
    ]
