# Generated by Django 5.0.6 on 2024-05-23 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0005_reserva_qntdatas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='qntDatas',
        ),
    ]
