# Generated by Django 5.0.6 on 2024-05-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0006_remove_reserva_qntdatas'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='qntDatas',
            field=models.IntegerField(default=0),
        ),
    ]
